---
driver:
  name: dokken
  chef_version: 12.15.19
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/secrets/secret_key"

verifier:
  name: inspec

platforms:
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release net-tools -y

suites:
  - name: default
    attributes:
      mail_domain: "nodomain"
      syslog:
        json:
          host: "127.0.0.1"
          port: 1000
      sentry_dsn:
        aes: "http://127.0.0.1"
    provisioner:
      policyfile: test/fixtures/policies/default.rb


